name: normal_distribution
description: A minimal Dart module for working with normal distributions.
version: 0.0.5
homepage: https://github.com/kaseken/normal_distribution

environment:
  sdk: '>=2.16.2 <4.0.0'

dev_dependencies:
  lints: ^1.0.0
  melos: ^6.3.2
  test: ^1.16.0
