name: normal_distribution
description: A minimal Dart module for working with normal distributions.
version: 1.0.0
homepage: https://github.com/kaseken/normal_distribution

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
